@startuml design

skinparam component {
    borderColor Black
    backgroundColor<<GameObject>> LightGray
    backgroundColor<<MonoBehaviour>> LightGreen
    backgroundColor<<ScriptableObject>> Tomato
    ArrowColor Black
    Text Bold
}

component Ninja <<GameObject>>
component Enemy <<GameObject>>
component Weapon <<GameObject>>
component Potion <<GameObject>>

component MoveBehaviour <<MonoBehaviour>>
component AttackBehaviour <<MonoBehaviour>>
component ControlBehaviour <<MonoBehaviour>>
component AIBehaviour <<MonoBehaviour>>
component InventoryBehaviour <<MonoBehaviour>>
component StorableBehaviour <<MonoBehaviour>>
component HealthEffectBehaviour <<MonoBehaviour>>
component ConsumableBehaviour <<MonoBehaviour>>

component ControlConfiguration <<ScriptableObject>>
component MoveConfiguration <<ScriptableObject>>
component AIConfiguration <<ScriptableObject>>
component InventoryConfiguration <<ScriptableObject>>
component StoreConfiguration <<ScriptableObject>>
component WeaponConfiguration <<ScriptableObject>>
component HealthEffectConfiguration <<ScriptableObject>>
component HealthConfiguration <<ScriptableObject>>

Ninja --> InventoryBehaviour
Ninja -left-> MoveBehaviour
Ninja --> ControlBehaviour
Ninja --> HealthConfiguration
Enemy --> InventoryBehaviour
Enemy -right-> MoveBehaviour
Enemy --> AIBehaviour
Enemy --> HealthConfiguration
Weapon --> AttackBehaviour
Weapon --> StorableBehaviour
Potion --> StorableBehaviour
Potion --> HealthEffectBehaviour
Potion --> ConsumableBehaviour

InventoryBehaviour --> InventoryConfiguration
StorableBehaviour --> StoreConfiguration
ControlBehaviour --> ControlConfiguration
MoveBehaviour -up-> MoveConfiguration
AIBehaviour --> AIConfiguration
AttackBehaviour --> WeaponConfiguration
HealthEffectBehaviour --> HealthEffectConfiguration

@enduml