@startuml (id=ninja)
!includeurl https://raw.github.com/jcawe/ninjaproject/master/Documentation/skin.wsd!skin

component Ninja <<GameObject>> {
    component MoveBehaviour <<MonoBehaviour>>
    component HealthBehaviour <<MonoBehaviour>>
    component ControlBehaviour <<MonoBehaviour>>

    ControlBehaviour -- OnHorizontalAxis
    ControlBehaviour -- OnVerticalAxis
    ControlBehaviour -- OnRun

    OnHorizontalAxis )-- MoveBehaviour : Horizontal(axis)
    OnVerticalAxis )-- MoveBehaviour : Vertical(axis)
    OnRun )-- MoveBehaviour : Run(axis)
}

component HealthProfile <<ScriptableObject>>
component MoveProfile <<ScriptableObject>>

HealthBehaviour -right- HealthProfile : <color:red><b>REQUIRES</b></color>
MoveBehaviour -right- MoveProfile : <color:red><b>REQUIRES</b></color>
@enduml

@startuml (id=enemy)
!includeurl https://raw.github.com/jcawe/ninjaproject/master/Documentation/skin.wsd!skin

component Enemy <<GameObject>> {
    component AIPatrolBehaviour <<MonoBehaviour>>
    component AIBladderBehaviour <<MonoBehaviour>>
    component AIPursuitBehaviour <<MonoBehaviour>>
    component ViewSensorBehaviour <<MonoBehaviour>>
    component BladderBehaviour <<MonoBehaviour>>
    component HealthBehaviour <<MonoBehaviour>>

    ViewSensorBehaviour -- OnDetected
    AIPursuitBehaviour -- OnTargetLost
    AIBladderBehaviour -up- OnPeeingStart
    AIBladderBehaviour -up- OnPeeingFinish

    OnPeeingStart )-up- AIPatrolBehaviour : enable = false
    OnPeeingFinish )-up- AIPatrolBehaviour : enable = true
    OnPeeingFinish )-up- BladderBehaviour : EmptyBladder()

    OnDetected )-up- AIPursuitBehaviour : Spotted(target)
    OnDetected )-- BladderBehaviour : enable = false
    OnDetected )-- AIPatrolBehaviour : enable = false

    OnTargetLost )-- AIPatrolBehaviour : enable = true
    OnTargetLost )-- BladderBehaviour : enable = true
}
component BladderProfile <<ScriptableObject>>
component HealthProfile <<ScriptableObject>>

BladderBehaviour -left- BladderProfile : <color:red><b>REQUIRES</b></color>
HealthBehaviour -right- HealthProfile : <color:red><b>REQUIRES</b></color>
@enduml

@startuml (id=spot)
!includeurl https://raw.github.com/jcawe/ninjaproject/master/Documentation/skin.wsd!skin

component ObjectLikeWC <<GameObject>> {
    component PeeSpot <<MonoBehaviour>>
}
@enduml

@startuml (id=others)

!includeurl https://raw.github.com/jcawe/ninjaproject/master/Documentation/skin.wsd!skin

component Weapon <<GameObject>>{
    component AttackBehaviour <<MonoBehaviour>>
    component StorableBehaviour <<MonoBehaviour>> as WStorable
}
component Potion <<GameObject>>{
    component HealthEffectBehaviour <<MonoBehaviour>>
    component ConsumableBehaviour <<MonoBehaviour>>
    component StorableBehaviour <<MonoBehaviour>> as PStorable
}

component HealthEffectProfile <<ScriptableObject>>

HealthEffectBehaviour -- HealthEffectProfile

component InventoryBehaviour <<MonoBehaviour>>

component MoveConfiguration <<ScriptableObject>>
component InventoryConfiguration <<ScriptableObject>>
component StoreConfiguration <<ScriptableObject>>
component WeaponConfiguration <<ScriptableObject>>

@enduml